name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Build
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Copy files to root for HACS
      - name: Prepare HACS release
        run: |
          cp dist/book-time-card.js .
          cp README.md .
          cp hacs.json .

      # Create a zip for HACS
      - name: ZIP the release
        run: |
          zip book-time-card.zip book-time-card.js README.md hacs.json

      # Upload zip for HACS
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: book-time-card.zip
          asset_name: book-time-card.zip
          tag: ${{ github.ref }}
          overwrite: true

      # Upload js file separately for manual installation
      - name: Upload js to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: book-time-card.js
          asset_name: book-time-card.js
          tag: ${{ github.ref }}
          overwrite: true
