name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Build
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Create HACS release structure
      - name: Create HACS release structure
        run: |
          # Create a clean directory for HACS release
          rm -rf hacs_release
          mkdir -p hacs_release

          # Copy all necessary files to root of release
          cp dist/book-time-card.js hacs_release/
          cp dist/book-time-card-*.js hacs_release/

          # Ensure the main file exists in root
          if [ ! -f "hacs_release/book-time-card.js" ]; then
            echo "Error: Main card file not found"
            exit 1
          fi

          # Copy required files
          cp README.md hacs_release/
          cp hacs.json hacs_release/

          # Verify the structure
          echo "=== Directory Structure ==="
          ls -la hacs_release/
          echo "=== hacs.json content ==="
          cat hacs_release/hacs.json
          echo "=== Main JS file size ==="
          ls -lh hacs_release/book-time-card.js

      # Create a zip for HACS
      - name: ZIP the release
        run: |
          cd hacs_release
          zip -r ../book-time-card.zip .
          echo "=== Zip file contents ==="
          unzip -l ../book-time-card.zip

      # Upload zip for HACS
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file: book-time-card.zip
          asset_name: book-time-card.zip
          tag: ${{ github.ref }}
          overwrite: true

      # Upload js file separately for manual installation
      - name: Upload js to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file: hacs_release/book-time-card.js
          asset_name: book-time-card.js
          tag: ${{ github.ref }}
          overwrite: true
